# Generated by Django 5.1.4 on 2025-06-09 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deal",
            options={"ordering": ["-date_of_deal"]},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["name", "-created"]},
        ),
        migrations.RemoveField(
            model_name="company",
            name="companies_house_id",
        ),
        migrations.RemoveField(
            model_name="company",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="company",
            name="monitors",
        ),
        migrations.AddField(
            model_name="company",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.country",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
