# Generated by Django 5.1.4 on 2025-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0002_alter_deal_options_alter_employee_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="companies_house_id",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
